pub(crate) mod apply;
pub(crate) mod daemon;
pub(crate) mod desktop;
pub(crate) mod doctor;
pub(crate) mod metrics;
pub(crate) mod panic;
pub(crate) mod profile;
pub(crate) mod rescue;
pub(crate) mod rollback;
pub(crate) mod run;
pub(crate) mod setup;
pub(crate) mod status;
pub(crate) mod suggest;
pub(crate) mod top;
#[cfg(feature = "tui")]
pub(crate) mod tui;
pub(crate) mod version;
